// GENERATED by `./gradlew generateVariants` from variants/catalog.json — do not edit by hand.
//
// Mutant anyof-no-short-circuit (conformant)
//   Combinators.kt:  override fun admits(duck: Duck): Boolean = policies.any { it.admits(duck) }  ->  override fun admits(duck: Duck): Boolean = policies.map { it.admits(duck) }.any { it }

package org.jetbrains.kotlin.course.duck.shop.admission

// The combinator policies — given, correct, and shared from :core. The idiomatic stdlib
// all{}/any{} give the vacuous-truth results (AllOf(emptyList())==true, AnyOf(emptyList())==false)
// for free.

/**
 * Admits a duck only when **every** policy in [policies] admits it (logical AND).
 */
class AllOf(private val policies: List<AdmissionPolicy>) : AdmissionPolicy {
    constructor(vararg policies: AdmissionPolicy) : this(policies.toList())

    override fun admits(duck: Duck): Boolean = policies.all { it.admits(duck) }
}

/**
 * Admits a duck when **at least one** policy in [policies] admits it (logical OR).
 */
class AnyOf(private val policies: List<AdmissionPolicy>) : AdmissionPolicy {
    constructor(vararg policies: AdmissionPolicy) : this(policies.toList())

    override fun admits(duck: Duck): Boolean = policies.map { it.admits(duck) }.any { it }
}

/**
 * Admits exactly the ducks that [policy] does **not** admit (logical NOT).
 */
class Not(private val policy: AdmissionPolicy) : AdmissionPolicy {
    override fun admits(duck: Duck): Boolean = !policy.admits(duck)
}
