// GENERATED by `./gradlew generateVariants` — do not edit by hand; edit the catalog.
//
// Mutant allof-fold (conformant): AllOf is written as a fold rather than with all {}.
//
// Compiles the real :core sources with Combinators.kt REPLACED by the modified copy under
// src/main, then runs a test suite against the result. This one is a legal refactoring:
// behaviour is unchanged, so a faithful suite stays GREEN here.

plugins {
    kotlin("jvm")
}

// Which suite runs against the mutant: "learner" (default) or any test source dir given as
// a path relative to this build's root — set with -PmutantTests=<learner|path>.
val suite: String = when (val selected = providers.gradleProperty("mutantTests").getOrElse("learner")) {
    "learner" -> "exercises/write-tests/src/test/kotlin"
    else -> selected
}

kotlin {
    jvmToolchain(21)

    sourceSets.named("main") {
        kotlin.srcDir(rootDir.resolve("core/src/main/kotlin"))
        kotlin.exclude("**/Combinators.kt")
    }
    sourceSets.named("test") {
        kotlin.srcDir(rootDir.resolve(suite))
        // The mutants target the admission-policy algebra; schedule tests need the
        // implementation modules, which are deliberately not on this classpath.
        kotlin.exclude("**/schedule/**")
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
    // verifyMutants reads the XML results, so a killed mutant must not break the build.
    ignoreFailures = true
}
