// GENERATED by `./gradlew generateVariants` from variants/catalog.json — do not edit by hand.
//
// Variant min-accessories-count (conformant)
//   Leaves.kt:  override fun admits(duck: Duck): Boolean = duck.accessories.size >= min  ->  override fun admits(duck: Duck): Boolean = duck.accessories.count() >= min

package org.jetbrains.kotlin.course.duck.shop.admission

// The leaf policies — given, correct, and shared from :core. Every exercise in the module is about
// specifying or checking this algebra, never about implementing it, so these are not what an agent
// writes.

/**
 * Admits only ducks that carry the Kotlin attribute.
 *
 * `admits(duck)` is `true` iff [Duck.hasKotlinAttribute] is `true`.
 */
class KotlinOnly : AdmissionPolicy {
    override fun admits(duck: Duck): Boolean = duck.hasKotlinAttribute
}

/**
 * Admits ducks whose price does not exceed [maxPrice].
 *
 * `admits(duck)` is `true` iff `duck.price <= maxPrice`.
 */
class MaxBudget(private val maxPrice: Int) : AdmissionPolicy {
    override fun admits(duck: Duck): Boolean = duck.price <= maxPrice
}

/**
 * Admits ducks that wear at least one accessory named [accessoryName].
 *
 * `admits(duck)` is `true` iff some accessory in [Duck.accessories] has that name.
 */
class RequiresAccessory(private val accessoryName: String) : AdmissionPolicy {
    override fun admits(duck: Duck): Boolean = duck.accessories.any { it.name == accessoryName }
}

/**
 * Admits ducks wearing at least [min] accessories.
 *
 * `admits(duck)` is `true` iff `duck.accessories.size >= min`.
 */
class MinAccessories(private val min: Int) : AdmissionPolicy {
    override fun admits(duck: Duck): Boolean = duck.accessories.count() >= min
}
